texto1_teste = 'este texto en minusculas'
texto2_test = 'ESTE TEXTO EN MAYUSCULAS'
nombre = 'Alejandro jimenez franco'
texto3_t = 'Este texto capitalizado'
apples_t = 4
aeppel_t = 159
formateo_t = "My name is Sebastian, I'm 25"
palabras_t = 'Hello World !'
texto4_t = 'programar'
texto5_t = 'jhon loves programming'
texto6_t = ['Hello', 'World,', 'today', 'is', 'a', 'great', 'day']
texto7_t = 169
texto8_t = 'El examen era mañana y yo a�n ten�a mucho que estudiar. Me tom� un vaso de leche con az�car, dej� de mirar el c�sped por la ventana de la habitaci�n y, aunque era dif�cil, me puse a estudiar como nunca antes hab�a hecho.'
