name: Taller NLP Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter nbconvert ipykernel
        python -m ipykernel install --user --name=python3
    
    - name: Ejecutar notebook ejercicio1
      run: |
        jupyter nbconvert --to notebook --execute notebooks/ejercicio1.ipynb --output ejercicio1_out.ipynb --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=300

    - name: Run tests ejercicio1
      run: |
        pytest tests/ejercicio1/ -v

    - name: Ejecutar notebook ejercicio2
      run: |
        jupyter nbconvert --to notebook --execute notebooks/ejercicio2.ipynb --output ejercicio2_out.ipynb --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=300
    
    - name: Run tests ejercicio2
      run: |
        pytest tests/ejercicio2/ -v
    
    - name: Ejecutar notebook ejercicio3
      run: |
        jupyter nbconvert --to notebook --execute notebooks/ejercicio3.ipynb --output ejercicio3_out.ipynb --ExecutePreprocessor.kernel_name=python3 --ExecutePreprocessor.timeout=300
    
    - name: Run tests ejercicio3
      run: |
        pytest tests/ejercicio3/ -v
